// 客户
export const ADD_NEW_COMPANY = 'ADD_NEW_COMPANY'
export const GET_ALL_COMPANY = 'GET_ALL_COMPANY'
export const GET_ALL_COMPANY_LENGTH  = 'GET_ALL_COMPANY_LENGTH'

// 账户
export const ADD_NEW_ACCOUNT = 'ADD_NEW_ACCOUNT'
export const GET_ALL_ACCOUNT = 'GET_ALL_ACCOUNT'
export const GET_ALL_ACCOUNT_LENGTH  = 'GET_ALL_ACCOUNT_LENGTH'
export const SER_CHARGE  = 'SER_CHARGE'
export const CHANGE_CREDIT  = 'CHANGE_CREDIT'
export const UPDATE_ALARM_LINE  = 'UPDATE_ALARM_LINE'
export const SET_PRICE  = 'SET_PRICE'
export const SET_SERVICE  = 'SET_SERVICE'

// 账户产品
export const GET_PRODUCT_PRICE_DETAIL = 'GET_PRODUCT_PRICE_DETAIL'
export const GET_PRODUCT_PRICE_DETAIL_LENGTH = 'GET_PRODUCT_PRICE_DETAIL_LENGTH'
export const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST'

// 变价记录
export const ACCOUNT_PRICE_RECORD = 'ACCOUNT_PRICE_RECORD'
export const ACCOUNT_PRICE_RECORD_LENGTH = 'ACCOUNT_PRICE_RECORD_LENGTH'

// 取消调价
export const CANCEL_WAIT_PRICE = 'CANCEL_WAIT_PRICE'

// 授信记录
export const CREDIT_RECORD = 'CREDIT_RECORD'
export const CREDIT_RECORD_LENGTH = 'CREDIT_RECORD_LENGTH'

// 充值记录 rechargeRecord
export const RECHARGE_RECORD = 'RECHARGE_RECORD'
export const RECHARGE_RECORD_LENGTH = 'RECHARGE_RECORD_LENGTH'