// 产品
export const ADD_NEW_PRODUCT = 'ADD_NEW_PRODUCT'
export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT'
export const GET_ALL_PRODUCT_LENGTH  = 'GET_ALL_PRODUCT_LENGTH'


// 计费字段
export const ADD_NEW_CHAEGE_FIELD = 'ADD_NEW_CHAEGE_FIELD'
export const GET_ALL_CHAEGE_FIELD = 'GET_ALL_CHAEGE_FIELD'
export const GET_ALL_CHAEGE_FIELD_LENGTH  = 'GET_ALL_CHAEGE_FIELD_LENGTH'


// 类型
export const ADD_NEW_TYPE = 'ADD_NEW_TYPE'
export const GET_ALL_TYPE = 'GET_ALL_TYPE'
export const GET_ALL_TYPE_LENGTH  = 'GET_ALL_TYPE_LENGTH'

// 定价规则
export const SET_PRICE_RULES  = 'SET_PRICE_RULES'
export const CANCEL_WAIT_PRICE  = 'CANCEL_WAIT_PRICE'

// 客户产品
export const PRODCUT_PRICE_DETAIL  = 'PRODCUT_PRICE_DETAIL'
export const PRODCUT_PRICE_DETAIL_LENGTH  = 'PRODCUT_PRICE_DETAIL_LENGTH'
export const ACCOUNT_PRODUCT_SETPRICE  = 'ACCOUNT_PRODUCT_SETPRICE'
export const ACCOUNT_PRODUCT_SETPRICE_FLAG  = 'ACCOUNT_PRODUCT_SETPRICE_FLAG'