const state = {
  allLabelList: [],
  allMenuList: [],
  allUserList: [],
  departmentList: [],
  addNewDepartmentFlag: false,
  addNewLabelFlag: false,
  allLabelListLength: 0,
  allRoleList: [],
  addNewRoleFlag: false,
  allRoleListLength: 0,
  allAttributeList: [],
  addNewAttributeFlag: false,
  allAttributeListLength: 0,
  addNewUserFlag: false,
  allUserListLength: 0,
  meunTreeList: [],
  addNewMeunFlag: false,
  allApplicationList: [],
  allApplicationListLength: 0,
  addNewApplicationFlag: false,
  menuActive: '',
  editableTabsValue: '',
  editableTabs: '',
  bindMeunFlag: false,
  resetAuthFormFlag: false,
  hasBindMenuList: [],
  defaultCheckedKeys: [],
}
export default state